apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qx7k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qx7k
    app.kubernetes.io/part-of: tkrw-pr714-0075-0010-app
  name: devfile-sample-qx7k
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qx7k
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qx7k
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0010-tenant/tkrw-pr714-0075-0010-app/devfile-sample-qx7k@sha256:618a2e02a3d1777944f09370d44568469b5134daf4708276f9ff476d7f8511bd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
